#!/usr/bin/env node
// Recruiting OS — mechanical setup helper.
//
// Does the boring, deterministic parts of onboarding so a freshly-cloned repo is ready to use:
//   • bundles supabase/migrations/*.sql (in order) into supabase/schema.sql for one-paste apply
//   • installs npm deps in webapp/ and mcp/skills-server/
//   • scaffolds webapp/.env.local from webapp/.env.example (never overwrites)
//   • creates the local-mode data/ scaffold
//   • writes recruiting-os.config.json from the example (never overwrites)
//   • prints the exact `claude mcp add` command with THIS clone's resolved path
//
// Safe to re-run. Node built-ins only (needs Node 18+). The interactive `/setup` skill orchestrates
// the human choices and calls this for the mechanical steps; you can also run it directly:
//
//   node scripts/setup.mjs [--storage=local|supabase] [--skip-install] [--help]

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const has = (flag) => args.includes(flag);
const opt = (name) => {
  const hit = args.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : undefined;
};

if (has("--help")) {
  console.log(
    "Usage: node scripts/setup.mjs [--storage=local|supabase] [--skip-install] [--help]",
  );
  process.exit(0);
}

const steps = [];
const log = (ok, msg) => {
  steps.push({ ok, msg });
  console.log(`${ok ? "✓" : "✗"} ${msg}`);
};

// ── Node version guard ────────────────────────────────────────────
const major = Number(process.versions.node.split(".")[0]);
if (major < 18) {
  console.error(
    `✗ Node ${process.versions.node} detected. Recruiting OS needs Node 18+ (20+ recommended).`,
  );
  process.exit(1);
}
log(true, `Node ${process.versions.node} OK`);

// ── Bundle migrations into a single schema.sql ────────────────────
const migrationsDir = path.join(repoRoot, "supabase", "migrations");
try {
  const files = fs
    .readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const banner =
    "-- GENERATED by scripts/setup.mjs — do not edit by hand.\n" +
    "-- Concatenation of supabase/migrations/*.sql in order. Paste into the Supabase\n" +
    "-- SQL editor of a FRESH project to create the full recruiting_ schema in one shot.\n\n";
  const body = files
    .map((f) => {
      const sql = fs.readFileSync(path.join(migrationsDir, f), "utf8").trim();
      return `-- ─────────────────────────────────────────────────────────────\n-- ${f}\n-- ─────────────────────────────────────────────────────────────\n${sql}\n`;
    })
    .join("\n");
  fs.writeFileSync(path.join(repoRoot, "supabase", "schema.sql"), banner + body);
  log(true, `Bundled ${files.length} migrations → supabase/schema.sql`);
} catch (err) {
  log(false, `Could not bundle migrations: ${err.message}`);
}

// ── Install deps ──────────────────────────────────────────────────
if (has("--skip-install")) {
  log(true, "Skipped npm install (--skip-install)");
} else {
  for (const dir of ["webapp", "mcp/skills-server"]) {
    const abs = path.join(repoRoot, dir);
    try {
      execFileSync("npm", ["install"], { cwd: abs, stdio: "inherit" });
      log(true, `Installed deps in ${dir}/`);
    } catch (err) {
      log(false, `npm install failed in ${dir}/ (${err.message.split("\n")[0]})`);
    }
  }
}

// ── Scaffold webapp/.env.local (never overwrite) ──────────────────
const envExample = path.join(repoRoot, "webapp", ".env.example");
const envLocal = path.join(repoRoot, "webapp", ".env.local");
if (fs.existsSync(envLocal)) {
  log(true, "webapp/.env.local already exists — left untouched");
} else if (fs.existsSync(envExample)) {
  fs.copyFileSync(envExample, envLocal);
  log(true, "Created webapp/.env.local from .env.example — fill in the 3 values");
} else {
  log(false, "webapp/.env.example missing — cannot scaffold .env.local");
}

// ── Local-mode data/ scaffold ─────────────────────────────────────
for (const d of [
  "data/profile/projects",
  "data/profile/experience",
  "data/crm/roles",
  "data/crm/contacts",
  "data/crm/interactions",
  "data/watchlist",
]) {
  fs.mkdirSync(path.join(repoRoot, d), { recursive: true });
}
log(true, "Created data/ scaffold (local-mode storage)");

// ── Write recruiting-os.config.json (never overwrite) ─────────────
const configPath = path.join(repoRoot, "recruiting-os.config.json");
const configExample = path.join(repoRoot, "recruiting-os.config.json.example");
if (fs.existsSync(configPath)) {
  log(true, "recruiting-os.config.json already exists — left untouched");
} else if (fs.existsSync(configExample)) {
  const cfg = JSON.parse(fs.readFileSync(configExample, "utf8"));
  const storage = opt("storage");
  if (storage === "local" || storage === "supabase") cfg.storage = storage;
  fs.writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n");
  log(true, `Wrote recruiting-os.config.json (storage: ${cfg.storage})`);
} else {
  log(false, "recruiting-os.config.json.example missing");
}

// ── Next steps ────────────────────────────────────────────────────
const serverPath = path.join(repoRoot, "mcp", "skills-server", "server.mjs");
console.log("\nNext steps");
console.log("──────────");
console.log("1. Register the skills MCP server (makes the /setup and skill commands available):");
console.log(
  `\n   claude mcp add --scope user recruiting-skills -- node ${serverPath}\n`,
);
console.log("2. In Claude Code, run the /setup skill to finish configuration interactively:");
console.log("   /mcp__recruiting-skills__setup   (or just: /setup)\n");
console.log("   Supabase storage → also create a Supabase project, paste supabase/schema.sql");
console.log("   into its SQL editor, and fill the 3 values in webapp/.env.local.");
console.log("   Local storage → nothing else needed; your data lives in data/.\n");

const failed = steps.filter((s) => !s.ok).length;
process.exit(failed ? 1 : 0);
